app/models/chatroom.rb
app/models/message.rb
db/migrate/20220228163234_create_messages.rb
db/migrate/20220228163510_create_chatrooms.rb
test/models/chatroom_test.rb
test/models/message_test.rb

added models of chatroom and message

added message and chatroom models

---

app/assets/stylesheets/components/_skill-card.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/skills/show.html.erb

polished skill show
avatar links

Skill index

---

app/controllers/skills_controller.rb
app/views/pages/home.html.erb

added a simple search for skills for demo

basic search

---

app/assets/stylesheets/pages/_userskill.scss
app/views/user_skills/show.html.erb

CSS of the Teacher profile and booking form improved

Css improved

---

app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

errors fixed

---

app/views/skills/index.html.erb

If else statement added for page result

If else statement added

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/components/_index.scss
app/channels/application_cable/connection.rb
app/channels/chatroom_channel.rb
app/controllers/chatrooms_controller.rb
app/controllers/messages_controller.rb
app/javascript/controllers/chatroom_subscription_controller.js
app/models/chatroom.rb
app/models/user.rb
app/policies/chatroom_policy.rb
app/policies/message_policy.rb
app/views/chatrooms/show.html.erb
app/views/messages/_message.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20220307092650_create_active_storage_tables.active_storage.rb
db/schema.rb
test/channels/chatroom_channel_test.rb

Cloudinary implemented.
Waiting for profile to be done to implement the form to allow user to add a picture.

Cloudinary

---

Gemfile.lock
app/javascript/controllers/index.js

Chatroom fix

---

.gitignore
app/assets/stylesheets/pages/_userskill.scss
app/controllers/application_controller.rb
app/views/user_skills/show.html.erb

disabled messages when not logged in

commit for sign in

---

app/controllers/bookings_controller.rb
app/models/chatroom.rb
app/views/chatrooms/show.html.erb

Accept and reject button are working
Css needs some works

Booking management

---

app/controllers/chatrooms_controller.rb
app/models/chatroom.rb
app/views/chatrooms/show.html.erb
app/views/shared/_my_bookings.html.erb
app/views/shared/_my_requests.html.erb

unicity of the chatroom should be done

Reviews unicity

---

app/views/shared/_my_bookings.html.erb
app/views/shared/_my_requests.html.erb
app/views/user_skills/show.html.erb

cloudinary key added

---

app/models/review.rb
app/models/user_skill.rb
db/migrate/20220309134732_add_references_to_user_skills.rb

Migration added for reviews in user skill

---

db/migrate/20220309134732_add_references_to_user_skills.rb

Migration fixed

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_icons.scss
app/assets/stylesheets/pages/_dashboard.scss
app/views/layouts/application.html.erb
app/views/pages/dashboard.html.erb
app/views/user_skills/show.html.erb
db/schema.rb

added icons

---

app/controllers/bookings_controller.rb
app/controllers/chatrooms_controller.rb
app/views/chatrooms/show.html.erb
app/views/shared/_my_bookings.html.erb
app/views/shared/_my_requests.html.erb
db/schema.rb

double chat fixed. There is now 1 room for 2 people.
Booking and request separated for better readability.
CSS needs some works

Fix double chat

---

app/assets/stylesheets/application.scss
app/javascript/packs/application.js
app/javascript/plugins/init_star_rating.js
app/views/shared/_my_bookings.html.erb
package.json
yarn.lock

Doesn't work.
Method is caught but don't understood

Star rating attempt

---

app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_skill-card.scss
app/javascript/controllers/mapbox_controller.js
app/views/skills/_info_window.html.erb

fixed css for skill cards and changed map pointers

changed css

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/pages/dashboard.html.erb
app/views/shared/_my_bookings.html.erb
app/views/shared/_my_requests.html.erb
app/views/shared/_navbar.html.erb

Dashboard css

---

Gemfile.lock
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_skills.scss

changed images

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/pages/dashboard.html.erb

fixed skill description , added hover to skill edit button

fixed skill description , added hover to skill edit button

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

added how it works to homepage

how it works again

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/users_controller.rb
app/views/pages/dashboard.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

coin on left side

---

Gemfile
Gemfile.lock
config/environments/test.rb
test/application_system_test_case.rb
test/system/skills_test.rb
test/test_helper.rb

Test attempt

---

app/controllers/application_controller.rb
config/database.yml
test/controllers/skills_controller_test.rb
test/fixtures/skills.yml
test/fixtures/user_skills.yml
test/fixtures/users.yml

Ready for review. Tests:
- the skill model
- index and show skills action
- show skills view

Test unit skills controller

---

test/controllers/user_skill_controller_test.rb
test/fixtures/user_skills.yml
test/fixtures/users.yml
test/helpers/test_helper.rb

Test ´"should show a user skill" initiated. It's falling for now.
Fixtures created

User skill test initiated

---

app/assets/stylesheets/components/_footer.scss
app/controllers/chatrooms_controller.rb
app/views/chatrooms/show.html.erb
app/views/shared/_footer.html.erb
tudent: @chatroom.student, teacher: @chatroom.teacher)

Name and link to the personal github added in the footer.
Designed adapted to welcome the name.

Footer name

---

app/controllers/chatrooms_controller.rb
app/policies/booking_policy.rb
app/policies/chatroom_policy.rb
app/policies/message_policy.rb
app/policies/review_policy.rb
app/policies/user_skill_policy.rb

Pundit policies have been corrected.

Pundit policies corrected

---

app/assets/stylesheets/components/_footer.scss
app/controllers/bookings_controller.rb
app/views/shared/_footer.html.erb

Coin logic is now asynchronous.
According if request is accepted, rejected, deleted, the student and teacher will receive the correct amount.
Booking controller has been refactored to keep it DRY.

Coins logic

---

app/assets/stylesheets/pages/_userskill.scss
app/controllers/user_skills_controller.rb
app/views/shared/_my_bookings.html.erb
app/views/user_skills/show.html.erb

Reviews readability improved.
Reviews and average rating separated in 2 lines
We can now see how many reviews there is and in the modal, the rating, title and comment for each reviews.

Reviews improvement

---

app/views/devise/registrations/new.html.erb

Changed sign up form photo -> "required: true"

photo now required on sign up
